services:
  vectordb:
    extends:
      file: compose.yml
      service: vectordb
    ports:
      - 6333:6333
      - 6334:6334
  text2sparql-virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    restart: unless-stopped
    ports:
      - "8890:8890"   # HTTP SPARQL endpoint
      - "1111:1111"   # ISQL interface
    environment:
      DBA_PASSWORD: dba
      #8 GB memory
      VIRT_Parameters_NumberOfBuffers: 680000
      VIRT_Parameters_MaxDirtyBuffers: 500000
      VIRT_Parameters_DirsAllowed: "., /dumps"
    volumes:
      - ./data/benchmarks/Text2SPARQL/virtuosodb:/database
      - ./data/benchmarks/Text2SPARQL/dumps:/dumps
  text2sparql-api:
    build: .
    restart: unless-stopped
    ports:
      - 8765:8765
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./data:/data
    env_file:
      - .env
    entrypoint: ["uv", "run", "uvicorn", "tests.text2sparql.api:app", "--host", "0.0.0.0", "--port", "8765", "--reload"]