services:

  vectordb:
    extends:
      file: compose.yml
      service: vectordb

  api:
    extends:
      file: compose.yml
      service: api
    # Required for podman-compose to resolve DNS properly
    dns:
      - 10.0.16.2
      - 10.0.16.3
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 80:8000
    environment:
      - AUTO_INIT=false
      # NOTE: dirty hack to fix a bug with podman internal network on prod server
      # - VECTORDB_URL=http://10.89.1.2:6334/
      # - DEFAULT_LLM_MODEL=openrouter/openai/gpt-5.1
      # - DEFAULT_LLM_MODEL=openrouter/mistralai/mistral-large
      # - DEFAULT_LLM_MODEL=openrouter/anthropic/claude-sonnet-4.5
      # - DEFAULT_LLM_MODEL=openai/gpt-4o-mini
    # entrypoint: ["uv", "run", "uvicorn", "src.sparql_llm.agent.main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--log-config", "logging.yml"]

# NOTE: some podman commands for debugging issues with podman compose networking
# podman-compose down && podman network prune -f
# podman exec -it sparql-llm_api_1 bash -c "apt-get update && apt-get install -y telnet && telnet vectordb 6334"
# < /dev/tcp/vectordb/6334
# podman exec -it api bash -c "< /dev/tcp/vectordb/6334"
